import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import nightwind from "nightwind/helper";

const defaultFont = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata = {
  title: "Jermaine Antwi | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/images/favicon.svg" sizes="any" />
      <script dangerouslySetInnerHTML={{ __html: nightwind.init() }}></script>
      <body className={`${defaultFont.className} bg-white`}>{children}</body>
    </html>
  );
}
