import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const defaultFont = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata = {
  title: "Jermaine Antwi | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/images/jermaine.logo.jpg" sizes="any" />
      <body className={defaultFont.className}>{children}</body>
    </html>
  );
}
